default linux

menu title Boot Menu

label linux
    menu label Linux 7.0
    kernel /Image
    fdt /qemu-arm64.dtb
	initrd /initrd.cpio.gz
    append console=ttyAMA0 earlycon=pl011,0x9000000 root=/dev/mmcblk0p2 rootwait rootfstype=ext4 rw loglevel=8 panic=5